#! /usr/bin/env python
#
# Copyright (c) 2011 by California Institute of Technology
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 
# 3. Neither the name of the California Institute of Technology nor
#    the names of its contributors may be used to endorse or promote
#    products derived from this software without specific prior
#    written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CALTECH
# OR THE CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
# USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.


"""
Accepts a *.aut filename and, optionally, a destination filename. If no
destination is given, default is to use input filename with "_trimmed"
appended.

Also note that command-line arguments are handled manually, since they
are so simple...

Originally written by Scott Livingston for GraphViz DOT files.

Modified by Yuchen Lin for automaton files.
"""

import sys
from subprocess import call

from tulip import grsim
from tulip.automaton import Automaton


if __name__ == "__main__":
    if len(sys.argv) < 2 or len(sys.argv) > 3:
        print "Usage: aut2gexf INPUT.aut [OUTPUT.gexf]"
        exit(1)

    if len(sys.argv) == 3:
        destfile = sys.argv[2]
    else:
        if len(sys.argv[1]) < 4:  # Handle weirdly short names
            destfile = sys.argv[1] + ".gexf"
        else:
            destfile = sys.argv[1][:-4] + ".gexf"
    
    aut_list = [Automaton(sys.argv[1])]
    
    # Generate graph of all automatons.
    grsim.writeStatesToFile(aut_list, destfile)

    # Display graph?
    if raw_input("Do you want to open in Gephi? (y/n)") == 'y':
        try:
            print "Opening GEXF file in Gephi."
            call(["gephi", destfile])
        except:
            print "Failed to open " + destfile + " in Gephi. Try:\n\n" + \
                  "gephi " + destfile + "\n\n"
