#!/usr/bin/env python
# Emacs, this is -*-Python-*-
"""
Convert an AUT file (from JTLV) to a tulipcon XML file.

This script is supposed to help those behind the times, who still work
with AUT files from JTLV.  Accepts a *.aut filename and, optionally, a
destination filename. If no destination is given, default is to use
input filename with new ending ".xml"

Also note that command-line arguments are handled manually, since they
are so simple...

Example: suppose you have robotctrl.aut from a JTLV session. Then to
generate a corresponding XML file, try

$ aut2xml robotctrl.{aut,xml}

Depending on your graphviz installation, the resulting image file may
be called robotctrl.dot.png
"""

import sys
from tulip.automaton import Automaton
from tulip.conxml import writeXMLfile

if __name__ == "__main__":
    if len(sys.argv) < 2 or len(sys.argv) > 4:
        print "Usage: aut2xml INPUT.aut [OUTPUT.xml]"
        exit(1)

    if len(sys.argv) == 3:
        destfile = sys.argv[2]
    else:
        if len(sys.argv[1]) < 4:  # Handle weirdly short names
            destfile = sys.argv[1] + ".xml"
        else:
            destfile = sys.argv[1][:-4] + ".xml"
    
    aut = Automaton(sys.argv[1])
    writeXMLfile(destfile, aut=aut, pretty=True)
