#!/usr/bin/env python
# Emacs, this is -*-Python-*-
"""
Generate a Gephi gexf file from tulipcon XML file.

Note this is basically a wrapper to ease use of the Automaton class,
readXML from the module conxml, and dumpGexf from the module
congexf. Accepts a *.xml filename and, optionally, a destination
filename. If no destination is given, default is to use input filename
with new ending ".gexf"

Also note that command-line arguments are handled manually, since they
are so simple...

SCL; 9 May 2012.
"""

import sys
from tulip.conxml import readXMLfile
from tulip.congexf import dumpGexf

if __name__ == "__main__":
    if len(sys.argv) < 2 or len(sys.argv) > 3:
        print "Usage: %s INPUT.xml [OUTPUT.gexf]" % sys.argv[0]
        exit(1)

    if len(sys.argv) == 3:
        destfile = sys.argv[2]
    else:
        if len(sys.argv[1]) < 4:  # Handle weirdly short names
            destfile = sys.argv[1] + ".gexf"
        else:
            destfile = sys.argv[1][:-4] + ".gexf"
    
    (prob, sys_dyn, aut) = readXMLfile(sys.argv[1])
    with open(destfile, "w") as f:
        f.write(dumpGexf([aut]))
